package com.gevernova.employeepayrollapp.entity;

import jakarta.persistence.Entity; // Use jakarta.persistence for Spring Boot 3+
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import lombok.*;

import java.util.Objects;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
@EqualsAndHashCode
@Entity
@Table(name = "employee_payroll") // Specifies the table name in the database
public class EmployeePayrollData {
    @Id // primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generates ID  (e.g., AUTO_INCREMENT in MySQL)
    @Column(name = "employee_id") //
    private int employeeId;

    @Column(name = "name")
    private String name;

    @Column(name = "salary")
    private long salary;

    // Overloaded constructor for POST/PUT requests where ID is generated by DB
    public EmployeePayrollData(String name, long salary) {
        this.name = name;
        this.salary = salary;
    }


}